[default]
proxy_proto_header=["X-Forwarded-Proto"]
port=443
address="0.0.0.0"
template_dir="app/templates"



[default.tls]
key="app/ssl/private_key.pem"
certs="app/ssl/certificate.pem"


[default.databases.primary]
url="app/database.sqlite"


[debug]
secret_key="6Zoa8SoaMlN++toh1BFO7rfEvAzon3KeX6szC+hUEhk="

