[default]
proxy_proto_header=["X-Forwarded-Proto"]
port=443
address="0.0.0.0"
#template_dir="server/templates"



[default.tls]
key="ssl/private_key.pem"
certs="ssl/certificate.pem"


[default.databases.primary]
url="database.sqlite"


[debug]
secret_key="6Zoa8SoaMlN++toh1BFO7rfEvAzon3KeX6szC+hUEhk="

